env:
  browser: true
  commonjs: true
  es6: true
  node: true
globals:
  phantom: true
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console: 1
