language: cpp
sudo: false
compiler:
  - gcc
cache: apt

addons:
  apt:
    packages:
    - gperf
    - libicu-dev
    - libssl-dev

before_script:
  - chmod +x ./build.sh
  - chmod +x ./test/run-tests-ghostdriver.sh
  
script:
  - ./build.sh --qtdeps=bundled --confirm --silent   #< Build
  - ./test/run-tests.py                              #< Test (PhantomJS)

notifications:
  irc:
    channels:
      - "irc.freenode.org#phantomjs"
    on_success: always
    on_failure: always
    use_notice: true
